# Generated by Django 4.0.6 on 2022-07-14 10:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Clan name', max_length=30, unique=True)),
                ('description', models.TextField(help_text='Clan description', max_length=300)),
                ('num_members', models.IntegerField(help_text='Number of members')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game_name', models.CharField(choices=[('lol', 'League of Legends'), ('rle', 'Rocket League'), ('val', 'Valorant'), ('csg', 'CS:GO'), ('fif', 'FIFA'), ('for', 'Fortnite'), ('wow', 'World of Warcraft')], help_text='Games to choose', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name', max_length=20)),
                ('last_name', models.CharField(help_text='Last name', max_length=40)),
                ('user_name', models.CharField(help_text='User name', max_length=20, unique=True)),
                ('email', models.EmailField(help_text='Email', max_length=30, unique=True)),
                ('password', models.CharField(help_text='Password', max_length=30)),
                ('language', models.CharField(choices=[('EN', 'English'), ('SP', 'Spanish'), ('FR', 'French'), ('GE', 'German'), ('CH', 'Chinese')], default='SP', help_text='Language', max_length=2)),
                ('profile_pic', models.ImageField(help_text='Profile pic', upload_to=None)),
                ('birth_date', models.DateField(help_text='Birth date')),
                ('role', models.CharField(choices=[('ad', 'Admin'), ('us', 'User')], default='us', help_text='Role privileges', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Gamer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='web.user')),
                ('discord', models.CharField(blank=True, help_text='Discord user name', max_length=30)),
                ('steam', models.CharField(blank=True, help_text='Steam user name', max_length=30)),
                ('epic_games', models.CharField(blank=True, help_text='EpicGames user name', max_length=30)),
                ('riot_games', models.CharField(blank=True, help_text='Riot Games user name', max_length=30)),
                ('status', models.CharField(choices=[('on', 'Online'), ('of', 'Offline'), ('pl', 'Playing')], default='off', help_text='Gamer status', max_length=2)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Clan', to='web.clan')),
            ],
        ),
        migrations.CreateModel(
            name='Gameship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.CharField(help_text='Gamer rank in a Game', max_length=20)),
                ('game', models.ForeignKey(help_text='Game selected', on_delete=django.db.models.deletion.CASCADE, to='web.game')),
                ('gamer', models.ForeignKey(help_text='Gamer that selects a Game', on_delete=django.db.models.deletion.CASCADE, to='web.gamer')),
            ],
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ac', 'Accepted'), ('de', 'Declined'), ('pe', 'Pending')], default='pe', help_text='Friendship request status', max_length=2)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Receiver', to='web.gamer')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sender', to='web.gamer')),
            ],
        ),
    ]
