# Generated by Django 4.0.6 on 2022-07-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='competitive',
            field=models.BooleanField(default=True, help_text='A game has competitive ranking or not'),
        ),
        migrations.AddField(
            model_name='game',
            name='game_rank',
            field=models.CharField(choices=[('CSG_RANKS', (('un', 'Unranked'), ('s1', 'Silver I'), ('s2', 'Silver II'), ('s3', 'Silver III'), ('s4', 'Silver IV'), ('se', 'Silver Elite'), ('sm', 'Silver Elite Master'), ('g1', 'Gold Nova I'), ('g2', 'Gold Nova II'), ('g3', 'Gold Nova III'), ('gm', 'Gold Nova Master'), ('m1', 'Master Guardian I'), ('m2', 'Master Guardian II'), ('me', 'Master Guardian Elite'), ('dm', 'Distinguished Master Guardian'), ('le', 'Legendary Eagle'), ('lm', 'Legendary Eagle Master'), ('sm', 'Supreme Master First Class'), ('ge', 'The Global Elite'))), ('LOL_RANKS', (('un', 'Unranked'), ('ir', 'Iron'), ('br', 'Bronze'), ('si', 'Silver'), ('go', 'Gold'), ('pl', 'Platinum'), ('di', 'Diamond'), ('ma', 'Master'), ('gm', 'Grand Master'), ('ch', 'Challenger'))), ('RLE_RANKS', (('un', 'Unranked'), ('br', 'Bronze'), ('si', 'Silver'), ('go', 'Gold'), ('pl', 'Platinum'), ('di', 'Diamond'), ('ch', 'Champion'), ('gc', 'Grand Champion'), ('le', 'Supersonic Legend'))), ('VAL_RANKS', (('un', 'Unranked'), ('ir', 'Iron'), ('br', 'Bronze'), ('si', 'Silver'), ('go', 'Gold'), ('pl', 'Platinum'), ('di', 'Diamond'), ('as', 'Ascendent'), ('in', 'Inmortal'), ('ra', 'Radiant')))], default='LOL_RANKS', help_text='Games ranks', max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_name',
            field=models.CharField(choices=[('LOL', 'League of Legends'), ('RLE', 'Rocket League'), ('VAL', 'Valorant'), ('CSG', 'CS:GO'), ('FIF', 'FIFA'), ('FOR', 'Fortnite'), ('WOW', 'World of Warcraft')], help_text='Games to choose', max_length=3),
        ),
    ]
