# Generated by Django 4.0.6 on 2022-07-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_game_competitive_game_game_rank_alter_game_game_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_rank',
        ),
        migrations.AlterField(
            model_name='gameship',
            name='rank',
            field=models.CharField(choices=[('un', 'Unranked'), ('CS:GO', (('s1', 'Silver I'), ('s2', 'Silver II'), ('s3', 'Silver III'), ('s4', 'Silver IV'), ('se', 'Silver Elite'), ('sm', 'Silver Elite Master'), ('g1', 'Gold Nova I'), ('g2', 'Gold Nova II'), ('g3', 'Gold Nova III'), ('gm', 'Gold Nova Master'), ('m1', 'Master Guardian I'), ('m2', 'Master Guardian II'), ('me', 'Master Guardian Elite'), ('dm', 'Distinguished Master Guardian'), ('le', 'Legendary Eagle'), ('lm', 'Legendary Eagle Master'), ('sm', 'Supreme Master First Class'), ('ge', 'The Global Elite'))), ('League of Legends', (('ir', 'Iron'), ('br', 'Bronze'), ('si', 'Silver'), ('go', 'Gold'), ('pl', 'Platinum'), ('di', 'Diamond'), ('ma', 'Master'), ('gm', 'Grand Master'), ('ch', 'Challenger'))), ('Rocket League', (('br', 'Bronze'), ('si', 'Silver'), ('go', 'Gold'), ('pl', 'Platinum'), ('di', 'Diamond'), ('ch', 'Champion'), ('gc', 'Grand Champion'), ('le', 'Supersonic Legend'))), ('Valorant', (('ir', 'Iron'), ('br', 'Bronze'), ('si', 'Silver'), ('go', 'Gold'), ('pl', 'Platinum'), ('di', 'Diamond'), ('as', 'Ascendent'), ('in', 'Inmortal'), ('ra', 'Radiant')))], default='un', help_text='Gamer rank in a Game', max_length=20),
        ),
    ]
