# Generated by Django 4.0.6 on 2022-07-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_user_last_online_delete_connectionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_online',
            field=models.DateField(blank=True, null=True),
        ),
    ]
