# Generated by Django 4.0.6 on 2022-07-14 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_game_game_rank_alter_gameship_rank'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gameship',
            unique_together={('game', 'gamer')},
        ),
    ]
