# Generated by Django 4.0.6 on 2022-07-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_user_is_online_alter_user_last_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_online',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
