# Generated by Django 4.0.6 on 2022-07-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_gameship_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(help_text='Profile pic', upload_to='img/profile'),
        ),
    ]
