# Generated by Django 4.0.6 on 2022-07-14 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamer',
            name='clan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Clan', to='web.clan'),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='status',
            field=models.CharField(choices=[('on', 'Online'), ('of', 'Offline'), ('pl', 'Playing')], default='of', help_text='Gamer status', max_length=2),
        ),
    ]
