# Generated by Django 4.0.6 on 2022-07-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_gameship_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameship',
            name='rank',
            field=models.CharField(choices=[('un', 'Unranked'), ('CSG', (('s1', 'Silver I'), ('s2', 'Silver II'), ('s3', 'Silver III'), ('s4', 'Silver IV'), ('se', 'Silver Elite'), ('sm', 'Silver Elite Master'), ('g1', 'Gold Nova I'), ('g2', 'Gold Nova II'), ('g3', 'Gold Nova III'), ('gm', 'Gold Nova Master'), ('m1', 'Master Guardian I'), ('m2', 'Master Guardian II'), ('me', 'Master Guardian Elite'), ('dm', 'Distinguished Master Guardian'), ('le', 'Legendary Eagle'), ('lm', 'Legendary Eagle Master'), ('sm', 'Supreme Master First Class'), ('ge', 'The Global Elite'))), ('LOL', (('ir', 'Iron'), ('br', 'Bronze'), ('si', 'Silver'), ('go', 'Gold'), ('pl', 'Platinum'), ('di', 'Diamond IV'), ('ma', 'Master IV'), ('gm', 'Grand Master'), ('ch', 'Challenger'))), ('RLE', (('b1', 'Bronze I'), ('b2', 'Bronze II'), ('b3', 'Bronze III'), ('s1', 'Silver I'), ('s2', 'Silver II'), ('s3', 'Silver III'), ('g1', 'Gold I'), ('g2', 'Gold II'), ('g3', 'Gold III'), ('p1', 'Platinum I'), ('p2', 'Platinum II'), ('p3', 'Platinum III'), ('d1', 'Diamond I'), ('d2', 'Diamond II'), ('d3', 'Diamond III'), ('c1', 'Champion I'), ('c2', 'Champion II'), ('c3', 'Champion III'), ('h1', 'Grand Champion I'), ('h2', 'Grand Champion II'), ('h3', 'Grand Champion III'), ('sl', 'Supersonic Legend'))), ('VAL', (('i1', 'Iron I'), ('i2', 'Iron II'), ('i3', 'Iron III'), ('b1', 'Bronze I'), ('b2', 'Bronze II'), ('b3', 'Bronze III'), ('s1', 'Silver I'), ('s2', 'Silver II'), ('s3', 'Silver III'), ('g1', 'Gold I'), ('g2', 'Gold II'), ('g3', 'Gold III'), ('p1', 'Platinum I'), ('p2', 'Platinum II'), ('p3', 'Platinum III'), ('d1', 'Diamond I'), ('d2', 'Diamond II'), ('d3', 'Diamond III'), ('c1', 'Ascendent I'), ('c2', 'Ascendent II'), ('c3', 'Ascendent III'), ('h1', 'Inmortal I'), ('h2', 'Inmortal II'), ('h3', 'Inmortal III'), ('rl', 'Radiant')))], default='un', help_text='Gamer rank in a Game', max_length=20),
        ),
    ]
