# Generated by Django 4.0.6 on 2022-07-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_game_game_ranks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameship',
            name='rank',
            field=models.CharField(blank=True, help_text='Gamer rank in a Game', max_length=20, null=True),
        ),
    ]
