# Generated by Django 4.1.1 on 2022-10-06 09:30

from django.db import migrations, models
import django.utils.timezone
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_game_game_ranks'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clan',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile/default.png', help_text='Profile pic', null=True, upload_to=web.models.Clan.image_upload_to),
        ),
    ]
