# Generated by Django 4.1.1 on 2022-10-06 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_clan_join_date_clan_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='join_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
