# Generated by Django 4.0.6 on 2023-01-09 11:26

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_clan_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile/default.png', help_text='Clan pic', null=True, upload_to=web.models.Clan.image_upload_to),
        ),
    ]
