# Generated by Django 4.0.6 on 2023-03-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_remove_game_game_ranks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameship',
            name='rank',
            field=models.CharField(blank=True, help_text='Gamer rank in a Game', max_length=100, null=True),
        ),
    ]
