# Generated by Django 4.0.6 on 2023-03-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_alter_gameship_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamer',
            name='discord',
            field=models.CharField(blank=True, help_text='Discord user name', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='epic_games',
            field=models.CharField(blank=True, help_text='EpicGames user name', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='riot_games',
            field=models.CharField(blank=True, help_text='Riot Games user name', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='steam',
            field=models.CharField(blank=True, help_text='Steam user name', max_length=30, null=True),
        ),
    ]
