# Generated by Django 4.0.6 on 2023-03-21 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_year', models.IntegerField()),
                ('language', models.CharField(max_length=2)),
                ('games_and_ranks_count', models.IntegerField()),
                ('num_friends', models.IntegerField()),
                ('similarity_vector', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
