# Generated by Django 4.0.6 on 2023-04-11 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_usermatrix_delete_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='TitleReport', max_length=100)),
                ('desc', models.TextField(help_text='DescReport', max_length=500)),
                ('type', models.CharField(help_text='TypeReport', max_length=100)),
                ('img', models.ImageField(blank=True, help_text='ImgReport', null=True, upload_to=web.models.Report.image_upload_to)),
                ('user', models.ForeignKey(help_text='UserReport', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
