# Generated by Django 4.0.6 on 2023-04-11 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_report_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
