# Generated by Django 4.0.6 on 2023-04-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('ac', 'Account'), ('us', 'User'), ('cl', 'Clan'), ('he', 'Help'), ('bu', 'Bugs and errors')], default='he', help_text='TypeReport', max_length=2),
        ),
    ]
