# Generated by Django 4.0.6 on 2023-04-12 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_alter_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('ve', 'Verification'), ('he', 'Help'), ('us', 'User'), ('bu', 'Bugs and errors'), ('ac', 'Account'), ('cl', 'Clan')], default='he', help_text='TypeReport', max_length=2),
        ),
    ]
