# Generated by Django 4.0.6 on 2023-04-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_alter_report_date_alter_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('bu', 'Bugs and errors'), ('us', 'User'), ('he', 'Help'), ('cl', 'Clan'), ('ac', 'Account'), ('ve', 'Verification')], default='he', help_text='TypeReport', max_length=2),
        ),
    ]
