# Generated by Django 4.0.6 on 2023-04-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_user_verified_alter_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('bu', 'Bugs and errors'), ('us', 'User'), ('he', 'Help'), ('ac', 'Account'), ('ve', 'Verification'), ('cl', 'Clan')], default='he', help_text='TypeReport', max_length=2),
        ),
    ]
