# Generated by Django 4.0.6 on 2023-04-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_alter_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('cl', 'Clan'), ('ve', 'Verification'), ('he', 'Help'), ('bu', 'Bugs and errors'), ('us', 'User'), ('ac', 'Account')], default='he', help_text='TypeReport', max_length=2),
        ),
        migrations.DeleteModel(
            name='UserMatrix',
        ),
    ]
