# Generated by Django 4.0.6 on 2023-04-13 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_alter_report_type_delete_usermatrix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('he', 'Help'), ('bu', 'Bugs and errors'), ('ac', 'Account'), ('us', 'User'), ('ve', 'Verification'), ('cl', 'Clan')], default='he', help_text='TypeReport', max_length=2),
        ),
    ]
