# Generated by Django 4.0.6 on 2023-04-13 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_alter_report_date_alter_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('he', 'Help'), ('ve', 'Verification'), ('us', 'User'), ('bu', 'Bugs and errors'), ('ac', 'Account'), ('cl', 'Clan')], default='he', help_text='TypeReport', max_length=2),
        ),
    ]
